spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reminder_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      
      # === [이 부분을 추가하세요] ===
      # 네이밍 전략(Naming Strategy)을 '물리적'으로(있는 그대로) 사용하도록 설정
      # 즉, @Table(name = "UserMedications")에 적힌 대소문자를 그대로 사용하라는 뜻입니다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
    properties:
      hibernate.format_sql: true